from src.dominio.excecoes.excecao_de_dominio import ExcecaoDeDominio
from src.dominio.excecoes.excecao_numero_de_ordem_de_matricula_invalido import ExcecaoNumeroDeOrdemDeMatriculaInvalido
from src.dominio.excecoes.excecao_data_de_matricula_invalida import ExcecaoDataDeMatriculaInvalida
from src.dominio.excecoes.excecao_tipo_de_imovel_de_matricula_invalido import ExcecaoTipoDeImovelDeMatriculaInvalido
from src.dominio.excecoes.excecao_tamanho_da_area_invalido import ExcecaoTamanhoDaAreaInvalido
from src.dominio.excecoes.excecao_medida_da_area_invalida import ExcecaoMedidaDaAreaInvalida
from src.dominio.excecoes.excecao_coordenadas_georreferenciadas_invalida import ExcecaoCoordenadasGeorreferenciadasInvalida
