from src.dominio.enums.enum_tipo_de_imovel import EnumTipoDeImovel
from src.dominio.enums.enum_opcoes_compartilhadas import EnumOpcoesCompartilhadas
from src.dominio.enums.enum_medida_da_area import EnumMedidaDaArea
