from src.dominio.matricula.enums.enum_tipo_de_imovel import EnumTipoDeImovel
from src.dominio.matricula.enums.enum_opcoes_compartilhadas import EnumOpcoesCompartilhadas
from src.dominio.matricula.enums.enum_medida_da_area import EnumMedidaDaArea
from src.dominio.matricula.enums.enum_formato_inscricao_imobiliaria_municipal import EnumFormatoInscricaoImobiliariaMunicipalDeMatricula
from src.dominio.matricula.enums.enum_coordenadas_georreferenciadas import EnumCoordenadasGeorreferenciadas
from src.dominio.matricula.enums.enum_cns_de_registro_anterior import EnumCNSDeRegistroAnterior
from src.dominio.matricula.enums.enum_formato_data_de_matricula import EnumFormatoDataDeMatricula
from src.dominio.matricula.enums.enum_formato_titulo_aquisitivo import EnumFormatoTituloAquisitivo
