from src.dominio.objetos_de_valor.numero_de_ordem_de_matricula import NumeroDeOrdemDeMatricula
from src.dominio.objetos_de_valor.data_de_matricula import DataDeMatricula
from src.dominio.objetos_de_valor.tipo_de_imovel_de_matricula import TipoDeImovelDeMatricula
from src.dominio.objetos_de_valor.tamanho_da_area import TamanhoDaArea
from src.dominio.objetos_de_valor.medida_da_area import MedidaDaArea
