from src.dominio.interfaces.interface_servico_ler_tabela import InterfaceServicoLerTabela
from src.dominio.interfaces.atributo_de_matricula import AtributoDeMatricula
from src.dominio.interfaces.agregado_de_matricula import AgregadoDeMatricula
